# Generated by Django 5.0.1 on 2024-01-24 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps_accounts", "0001_initial"),
        ("apps_core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="userprofile",
            name="unique_constraint_document_type_document_number_and_country_has_unique",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="country_user_profile_related",
                to="apps_core.countries",
            ),
        ),
        migrations.AddConstraint(
            model_name="userprofile",
            constraint=models.UniqueConstraint(
                fields=("document_type", "document_number", "country"),
                name="unique_constraint_user_profile_document_type_document_number_and_country_has_unique",
            ),
        ),
    ]
