# Generated by Django 5.0.1 on 2024-01-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "apps_accounts",
            "0002_remove_userprofile_unique_constraint_document_type_document_number_and_country_has_unique_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("MADRE", "Madre"),
                    ("PADRE", "Padre"),
                    ("TUTOR", "Tutor"),
                    ("PROFESOR", "Profesor"),
                ],
                default="MADRE",
                max_length=10,
            ),
        ),
    ]
