from cerberus.errors import BasicErrorHandler


class CustomErrorHandler(BasicErrorHandler):
    messages = {
        0x27: "la longitud mínima para {field} es {constraint}: Valor enviado {value}",
        0x28: "la longitud máxima para {field} es {constraint}",
        0x41: "El correo que enviado para {field} no es valido: Valor enviado {value}",
        0x42: "El valor minimo para {field} es {constraint}",
        0x43: "El valor máximo para {field} es {constraint}",
        0x24: "Para {field} debe ser de tipo {constraint}: Valor enviado {value}",
        0x02: "El campo es requerido",
        0x22: "los valores vacíos no están permitidos",
        0x03: "Campo desconocido, porfavor no modifique los campos",
        0x04: "Campo '{0}' es requerido",
        0x44: "Valor {value} no permitido. Los valores permitidos son exactamente esto: {constraint}",
        0x45: "Valores no permitido {0}",
        0x46: "Valor {value} no permitido. Los valores permitidos son exactamente esto: {constraint}",
        0x47: "Valores no permitido {0}",
        0x00: "{0}",
        0x01: "document is missing",
        0x05: "depends on these values: {constraint}",
        0x06: "{0} must not be present with '{field}'",
        0x21: "'{0}' is not a document, must be a dict",
        0x23: "null value not allowed",
        0x25: "must be of dict type",
        0x26: "length of list should be {0}, it is {1}",
        0x48: "missing members {0}",
        0x61: "field '{field}' cannot be coerced: {0}",
        0x62: "field '{field}' cannot be renamed: {0}",
        0x63: "field is read-only",
        0x64: "default value for '{field}' cannot be set: {0}",
        0x81: "mapping doesn't validate subschema: {0}",
        0x82: "one or more sequence-items don't validate: {0}",
        0x83: "one or more keys of a mapping  don't validate: {0}",
        0x84: "one or more values in a mapping don't validate: {0}",
        0x85: "one or more sequence-items don't validate: {0}",
        0x91: "one or more definitions validate",
        0x92: "none or more than one rule validate",
        0x93: "no definitions validate",
        0x94: "one or more definitions don't validate",
    }
